name: Release

on:
  push:
    tags:
    - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build linux amd64
      run: go build -o geesefs-linux-amd64 -v && ln -s geesefs-linux-amd64 geesefs

    - name: Build Mac amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o geesefs-mac-amd64 -v

    - name: Build Mac arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o geesefs-mac-arm64 -v

    - name: Publish to S3
      run: |
        sudo apt-get -y install s3cmd
        s3cmd ${{secrets.S3CMD}} put geesefs-linux-amd64 s3://${{secrets.S3BUCKET}}/geesefs-linux-amd64
        s3cmd ${{secrets.S3CMD}} put geesefs-mac-amd64 s3://${{secrets.S3BUCKET}}/geesefs-mac-amd64
        s3cmd ${{secrets.S3CMD}} put geesefs-mac-arm64 s3://${{secrets.S3BUCKET}}/geesefs-mac-arm64
        s3cmd ${{secrets.S3CMD}} put geesefs-linux-amd64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/geesefs-linux-amd64
        s3cmd ${{secrets.S3CMD}} put geesefs-mac-amd64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/geesefs-mac-amd64
        s3cmd ${{secrets.S3CMD}} put geesefs-mac-arm64 s3://${{secrets.S3BUCKET}}/${GITHUB_REF/refs\/tags\/v/}/geesefs-mac-arm64

    - name: Test
      run: make run-test

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          geesefs-linux-amd64
          geesefs-mac-amd64
          geesefs-mac-arm64

    - name: Run xfstests
      # Often crashes in CI due to memory limits
      continue-on-error: true
      run: make run-xfstests
      timeout-minutes: 10
